### ISSUE TITLE
Brique de Dataviz ?

### ISSUE THREAD

**Issue by armgilles** [dataforgoodfr/batch_5_transplant#27]
Je vois pas mal de discussions autour des données (Slack et réunions). 

Comme ce n'est pas simple de pouvoir se rendre compte de l'état d'un patient avec un ```data.head()``` ou dans un fichier Excel,

Je pensais introduire une façon d'analyser rapidement les données et de façon temporelle. Cette issue est l'occasion d'en discuter / brainstormer. 

**PR soon**

### Objectif premier : 

- Pouvoir analyser un patient à un moment précis avec un ou plusieurs indicateurs.

### Objectif second : 

- Comparer visuellement 2 patients sur des indicateurs communs afin de pouvoir comprendre le résultat de l'algo [rétro-analyse des résultats de l'algo]

### Aide Features Engineering : 

- Pouvoir tester et regarder une nouvelle feature et son interaction avec les autres rapidement.

### Contrainte : 

- Etre une brique totalement indépendante du projet. Ainsi les données en entrées peuvent être les données original, données temporaire ou des données déjà process (cf PR classes).

## Questions : 

- Ou mettre ces briques de data-viz dans le projet ?
- Type de graphiques ?
- Autres besoins à définir ?

## Réalisation actuelle : 

![enregistrement de l ecran 2018-12-05 a 17 48 35](https://user-images.githubusercontent.com/8374843/49529619-b76e5e00-f8b6-11e8-9465-bc85fc95531e.gif)

**Comment by martindaniel4** [comment]
Fixed in https://github.com/dataforgoodfr/batch_5_transplant/pull/30
