### ISSUE TITLE
[Donnees dynamiques] 55 patients manquent dans les donnees dynamiques

### ISSUE THREAD

**Issue by DatenBiene** [dataforgoodfr/batch_5_transplant#33]
Il semble y avoir un delta d'environ 30 patients entre le train set  de static et le train set de dynamic ... 

![image](https://user-images.githubusercontent.com/20189371/49730716-8789d680-fc79-11e8-98b4-6fd8663d9ca8.png)

Tous les patients de dynamic sont bien dans static mais non l'inverse de par ceci : 

![image](https://user-images.githubusercontent.com/20189371/49730866-eea78b00-fc79-11e8-8dc4-1a3c555fd797.png)

De plus nous avons sans doute le même problème pour le test set.
 
Questions : 
Où sont les données opératoires manquantes ? 
Avons-nous des patients présents dans dynamic mais pas dans static ?

**Comment by martindaniel4** [comment]
@julienfessler any ideas?

**Comment by julienfessler** [comment]
je n'ai pas compris la question

**Comment by armgilles** [comment]
Je confirme, il y a bien : 
 - 410 patients dans les données `static`
- 355 patients dans les données `dynamic`

Liste des patients absents dans les données `dynamic`: 

```
print(abs_patient_dyna) # différence entre les patients de static & dynamic

[5, 8, 28, 69, 104, 162, 165, 169, 173, 183, 190, 196, 212, 242, 261, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 303, 306, 307, 310, 313, 317, 321, 324, 332, 339, 345, 348, 350, 353, 365, 374, 385, 402]

# Vérification (lecture du fichier dynamic) 
df = pd.read_csv(PATH_DYNAMIC_CLEAN, parse_dates=['time'])

len(df[df.id_patient.isin(abs_patient_dyna)])
# 0 
```

Il nous manque donc 55 patients dans les données `dynamic`

**Comment by martindaniel4** [comment]
@mleguenD4G : des idées sur pourquoi 55 patients manquent à la base dynamique ?

**Comment by julienfessler** [comment]
en cours...

**Comment by Max-Pol** [comment]
Parfait !

**Comment by martindaniel4** [comment]
@mleguenD4G, après avoir intégré le fichier bloc5, on trouve toujours des patients manquants. Voici leur `id_patient`: 

```
[5,   8,  28,  69, 104, 162, 165, 169, 173, 183, 190, 196, 212,
       242, 261, 278, 286, 293, 303, 306, 307, 310, 313, 317, 321, 324,
       332, 339, 345, 348, 350, 353, 365, 374, 385, 402]
```

Sais tu dans quel fichier nous devrions les retrouver? As tu une idée sur pourquoi ils ne sont pas transmis dans ces fichiers à date?

**Comment by martindaniel4** [comment]
Fixed dans cette PR - https://github.com/dataforgoodfr/batch_5_transplant/pull/58
