### ISSUE TITLE
Données dynamiques - Nombre important de valeurs NA 

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/batch_5_transplant#34]
Un nombre important de variables dynamiques ont des valeurs NA. Cela est problématique pour la constitution de features de variables dynamiques. 

- Est ce que cela provient de prise de mesure non continues (par exemple rythme cardiaque pris durant un clampage?) 
- Comment devons nous traiter les valeurs NA? Devons nous les mettre à 0? Ignorer les entrées? 
- Est-ce une erreur et auquel cas pouvons nous récupérer des données? 

```
MAC             0.858164
SvO2 (m)        0.752939
ETCO2 (mmHg)    0.740506
FICO2 (mmHg)    0.740506
DC              0.665958
Pplat           0.617142
Temp            0.469931
VT              0.465220
ET Des.         0.376986
FR(ecg)         0.375997
BIS SR          0.274832
B.I.S           0.274832
PAPsys          0.217809
PAPmoy          0.217809
PAPdia          0.216482
SpO2            0.200744
RR(co2)         0.131927
PASs            0.111853
PASd            0.111853
PASm            0.111853
etc..
```

**Comment by martindaniel4** [comment]
@julienfessler - Hésite pas à donner ton avis!

**Comment by mleguenD4G** [comment]
pour répondre à la question des NA -
c'est dans la base complète ou hémodynamique?
si complète, on doit pouvoir compléter à partir de hémodynamique. Si HD, données non récupérées et donc non récupérable

**Comment by martindaniel4** [comment]
@mleguenD4G c'est dans toutes les données dynamiques en fait. Si je prends juste les données dynamiques de `haemodynamiques` voici la part des données `NA`: 

```
variable
DC        0.665958
PAPsys    0.217809
PAPmoy    0.217809
PAPdia    0.216482
PASs      0.111853
PASm      0.111853
PASd      0.111853
PNIs      0.081096
PNIm      0.050180
PNId      0.028134
FC        0.001523
```

Pourquoi par exemple 66% des valeurs du débit cardiaque sont `NA` ?

**Comment by mleguenD4G** [comment]
Bonsoir, 
 
Je viens de regarder dans la base pour ce qui est des valeurs de DC et de ETCO2
- DC: c'est une valeur qu'on obtient qu'après 2 heures de présence au bloc opératoire car il s'agit d'un capteur posé une fois le patient endormi, avec un accès particulier au cou et démarré en général juste avant l'incision. Ceci explique une partie de l'absence de valeurs à la phase initiale. Par aillerus, la valeur de DC est donnée par le même capteur que SvO2, sauf qu'il y a une calibration en plus et que parfois celle ci ne marche pas et donc des patients ont 0 toute l'intervention car le capteur est bien présent mais n'est pas capable de traiter l'information
 
- ETCO2: de façon aléatoire dans les inclusions, des patients ont soit la valeur en kPa soit en mmHg. Il n'y a jamais de mélange pour un patient donné mais la valeur exporté est aléatoire!! je ne m'en étais pas aperçu jusqu'à présent.
pour répondre à la question du jour; on peut avoir des valeurs très élevées, on n'aime pas mais ce sont des valeurs plausibles
 
amitiés scientistes
 
morgan
 
Dr Morgan Le Guen
Anesthésiste-Réanimateur
Hôpital Foch, Suresnes

DECT: + 33 1 46 25 29 98
tél: + 33 1 46 25 24 33 
-----Martin Daniel <notifications@github.com> a écrit : ----- 

A : dataforgoodfr/batch_5_transplant <batch_5_transplant@noreply.github.com>De : Martin Daniel <notifications@github.com>Date : 11/12/2018 15:57Cc: mleguenD4G <m.leguen@hopital-foch.org>, Mention <mention@noreply.github.com>Objet : Re: [dataforgoodfr/batch_5_transplant] Données dynamiques - Nombre important de valeurs NA (#34)
@mleguenD4G c'est dans toutes les données dynamiques en fait. Si je prends juste les données dynamiques de haemodynamiques voici la part des données NA:
variableDC        0.665958PAPsys    0.217809PAPmoy    0.217809PAPdia    0.216482PASs      0.111853PASm      0.111853PASd      0.111853PNIs      0.081096PNIm      0.050180PNId      0.028134FC        0.001523
Pourquoi par exemple 66% des valeurs du débit cardiaque sont NA ?

**Comment by martindaniel4** [comment]
Super intéressant @mleguenD4G. Cc @armgilles @DatenBiene @Max-Pol

**Comment by martindaniel4** [comment]
Merci @armgilles pour le deep-dive !

Est il possible de récupérer les données DC manquantes pour les 230 patients qui n'ont pas de valeurs @mleguenD4G ou est ce que c'est perdu ?

Pour la variable `ETCO2` on pourrait, en fonction des seuils, créer une petite fonction qui determine si la variable est en Kpa ou en mmHg ?

**Comment by mleguenD4G** [comment]
bonjour à tousje suis en train de regarder les data hémodynamiques manquantes depuis l'hôpital;vous n'auriez pas aisément les numéros de patients car j'ai les tables initiales XXXXD4G mais les numéros sont dans un ordre aléatoire...je checke des tables au hasard mais c'est un peu long. Bonnes courses de Noel à ceux qui ne répondront pas de suite!!!morgan Dr Morgan Le GuenAnesthésiste-RéanimateurHôpital Foch, SuresnesDECT: + 33 1 46 25 29 98tél: + 33 1 46 25 24 33-----Martin Daniel <notifications@github.com> a écrit : -----A : dataforgoodfr/batch_5_transplant <batch_5_transplant@noreply.github.com>De : Martin Daniel <notifications@github.com>Date : 11/12/2018 22:01Cc: mleguenD4G <m.leguen@hopital-foch.org>, Mention <mention@noreply.github.com>Objet : Re: [dataforgoodfr/batch_5_transplant] Données dynamiques - Nombre important de valeurs NA  (#34)Super intéressant @mleguenD4G. Cc @armgilles @DatenBiene @Max-Pol

**Comment by mleguenD4G** [comment]
j'ai trouvé dans un des écrits de clémentje regarde et tente de vous livrer le set manquant s'il existe bien....Dr Morgan Le GuenAnesthésiste-RéanimateurHôpital Foch, SuresnesDECT: + 33 1 46 25 29 98tél: + 33 1 46 25 24 33-----Morgan LE GUEN/BLOC/MEDT/HOPITAL-FOCH a écrit : -----A : dataforgoodfr/batch_5_transplant <reply@reply.github.com>De : Morgan LE GUEN/BLOC/MEDT/HOPITAL-FOCHDate : 16/12/2018 16:41Cc: dataforgoodfr/batch_5_transplant <batch_5_transplant@noreply.github.com>, Mention <mention@noreply.github.com>Objet : Re: [dataforgoodfr/batch_5_transplant] Données dynamiques - Nombre important de valeurs NA  (#34)bonjour à tousje suis en train de regarder les data hémodynamiques manquantes depuis l'hôpital;vous n'auriez pas aisément les numéros de patients car j'ai les tables initiales XXXXD4G mais les numéros sont dans un ordre aléatoire...je checke des tables au hasard mais c'est un peu long. Bonnes courses de Noel à ceux qui ne répondront pas de suite!!!morgan Dr Morgan Le GuenAnesthésiste-RéanimateurHôpital Foch, SuresnesDECT: + 33 1 46 25 29 98tél: + 33 1 46 25 24 33-----Martin Daniel <notifications@github.com> a écrit : -----A : dataforgoodfr/batch_5_transplant <batch_5_transplant@noreply.github.com>De : Martin Daniel <notifications@github.com>Date : 11/12/2018 22:01Cc: mleguenD4G <m.leguen@hopital-foch.org>, Mention <mention@noreply.github.com>Objet : Re: [dataforgoodfr/batch_5_transplant] Données dynamiques - Nombre important de valeurs NA  (#34)Super intéressant @mleguenD4G. Cc @armgilles @DatenBiene @Max-Pol

**Comment by martindaniel4** [comment]
Duplicate of https://github.com/dataforgoodfr/batch_5_transplant/issues/41
