### ISSUE TITLE
Données dynamiques - Anomalies & remarques

### ISSUE THREAD

**Issue by armgilles** [dataforgoodfr/batch_5_transplant#39]
Suite à #28 puis #34 j'ai regarder l'ensemble des données dynamiques (transplant.tools.dataset.get_dynamic() ) que l'on a. Il s'avère qu'un grand nombre de ces variables ont de possibles problèmes d'unités ou d'erreurs machine ou autres... (bref à voir avec le métier).

J'ai crée un [gist](https://gist.github.com/armgilles/29de2ace416ff7719c43d1d98a9af0e8) afin de lister toutes les variables.

@martindaniel4 Je pense que ça sera parfait comme doc pour la réunion de ce soir.

**Comment by martindaniel4** [comment]
Ah mortel @armgilles ! 

@mleguenD4G and @julienfessler pour info. Discutons en ce soir si vous pouvez venir!

**Comment by martindaniel4** [comment]
@armgilles je ferme cette PR, sachant que nous avons une issue créé par problème identifié de data quality.
