### ISSUE TITLE
[Donnees Dynamiques] Exporter les donnees B.I.S manquantes

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/batch_5_transplant#40]
Un certain nombre de patients ont des valeurs allant de 0 à 8 (patient 184, 193, 200) alors que la plupart des valeurs vont de 0 à 100. Double unité ?

- Il est possible que des valeurs de B.I.S soient comprises entre 0 et 15. C’est plutot un mauvais signe lorsque cet indicateur est soutenu. 
- Nous remarquons qu’un certain nombre de patients ont des valeurs B.I.S nulles. Cela correspond a un probleme d’export de donnees et peut etre recupere par un nouvel export.

**Comment by mleguenD4G** [comment]
avez vous comme pour les DC, les numéros de patients correspondant sans BIS afin que je regarde s'il existe un moyen de récupérer les données sur  un autre support (prototype de robot anesthésie)
morgan

**Comment by martindaniel4** [comment]
@mleguenD4G en reprenant les nouvelles données suite au fix de Max - https://github.com/dataforgoodfr/batch_5_transplant/pull/44, je trouve 116 patients qui ont des valeurs de B.I.S nulles plus de 10 fois dans le set. Voici la liste: 

```
array([149, 151, 155, 113, 193, 121,  52, 136, 209, 240, 131, 188, 110,
        60, 221,  68, 122,  24,  97, 123,  38, 199,  93, 225,  53,  72,
       117, 100,  43,  98, 107,  42, 202, 132, 120, 211, 177, 182, 175,
       111, 118, 156, 114, 239,  88,  66,  91, 153,  11, 161, 129, 138,
       125,  48, 160,  56,   1, 105,  70, 115, 170,  78,  64, 101, 181,
        21, 195,  87, 409,  73, 150, 134, 241,  81,  65,  85,   3, 228,
       147,  12, 119, 200, 184,  41,   2,  75,  79,  83, 404,  82,  99,
        16, 141,  55,  92, 116,  59,  47, 102,  54,  45, 164, 127,   6,
        57,  51,  37,  76, 351, 203,  10, 171, 172, 103, 255, 201])
```

**Comment by martindaniel4** [comment]
On ne va pas exporter les B.I.S manquantes car trop compliqué.
