### ISSUE TITLE
[Dynamic Data] Les colonnes parsees dans les colonnes des fichiers Bloc sont incorrectes

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/batch_5_transplant#41]
Les données bloc ont un bloc de patient exportée au sein d'une meme feuille de calcul. En consequence, il est possible que la meme colonne contienne des valeurs différentes. 

E.g dans le fichier `Bloc3D4G.xls`: 

![screen shot 2018-12-12 at 8 44 24 pm](https://user-images.githubusercontent.com/695006/49894667-d177e580-fe4e-11e8-892d-826226680a18.png)

@Max-Pol - cette ligne du parser est en réalité incorrecte - https://github.com/dataforgoodfr/batch_5_transplant/blob/master/transplant/data/build_clean_from_raw_data.py#L23

@armgilles avait créé un parser pour gérer ces cas ici - https://github.com/dataforgoodfr/batch_5_transplant/blob/armand_analyse_factory/scripts/parser.py#L48

**Comment by armgilles** [comment]
J'avais fait une analyse du pipeline pour traiter les fichiers dynamic (fichier xls mal structuré). Le noteebook est [LA](https://github.com/dataforgoodfr/batch_5_transplant/blob/083fc8d0ba54dd64bfc1f399c4ff8b9615230879/notebooks/1_analyse_preliminaire_new_data_excel.ipynb).

J'essayer de merge ça avec le code actuelle.

WIP

**Comment by Max-Pol** [comment]
Salut !

Ah oui en effet c'est bien dégeulasse tout ça ! Heureusement que vous aviez remarqué cela... J'ai fait une [PR](https://github.com/dataforgoodfr/batch_5_transplant/pull/44) qui devrait corriger tout ça.

**Comment by armgilles** [comment]
Question bête donc utile : 

Si je prend le patient n°`151`, dans les données `dynamic`(fichier Bloc9D4G.xls) on peut voir le début de l'opération à  **16/10/2011 à 19:19**. 

![image](https://user-images.githubusercontent.com/8374843/49952207-caf37780-fefb-11e8-98ca-b43b0cfdd036.png)


Pourtant lorsque je regarde dans les données `static` la `date_transplantation` je n'ai pas la même date...

![image](https://user-images.githubusercontent.com/8374843/49952085-aac3b880-fefb-11e8-9334-2f3ec7d76136.png)

J'ai raté quelques choses @martindaniel4 @Max-Pol ?

**Comment by Max-Pol** [comment]
Ah l'horreur... 

@armgilles Bien vu, il y a manifestement une incohérence, on ne peut pas faire grand chose à part voir avec Julien pour corriger... 

Alors une remarque importante, j'ai ignoré les deux colonnes sans nom après `id_patient` et `time` que tu montres dans les XLS dynamic, qui représentent la date de transplantation & je-ne-sais quoi, car elles ne sont pas présentes dans tous les fichiers et redondantes avec static (où la `date transplantation` est bien présente dans tous les cas). Du coup, on considère que STATIC est la vérité pour l'instant si ça te va

**Comment by armgilles** [comment]
@Max-Pol Je ne prenais pas non plus ces colonnes, mais quand j'ai voulu regarder de plus près les données dans les fichiers .xls je suis tombé dessus. Et comme la curiosité est un vilain défaut, j'ai direct regardé dans les données `statics`... Je ne pense pas que le jour de l'opération soit important pour la suite. 

Je serais pas contre une confirmation du métier sur cette date quand même, est ce que tu peux assigner quelqu'un @martindaniel4 ?

**Comment by martindaniel4** [comment]
@julienfessler, @mleguenD4G - pourriez vous nous éclairer sur la question de la date des fichiers dynamiques vs date opération données statiques? Le patient `151` par exemple, n'a pas de date qui corresponde entre le fichier statique et les données dynamiques.

**Comment by martindaniel4** [comment]
@Max-Pol - on peut la fermer celle-ci ? Il me semble que cette PR fait le job https://github.com/dataforgoodfr/batch_5_transplant/pull/44 ?
