### ISSUE TITLE
Encoding des heures evenements (clampage, declampage)

### ISSUE THREAD

**Issue by Karinehoo** [dataforgoodfr/batch_5_transplant#56]

**Comment by armgilles** [comment]
Suite à une analyse préliminaire, il semble qu'un certains nombres de patients n’ait pas données pour `Heure_declampage_cote1` ou `Heure_declampage_cote2`. 

### Questions ?

- Est-ce c'est normal si un patient n'a pas de données dans `Heure_declampage_cote2` mais une heure indiquée dans `Heure_declampage_cote1` (une seule transplantation ) ?

- Est-ce possible qu'un patient n'ait aucune heure de déclampage renseigné ?

Ci-dessous l'image des patients

![image](https://user-images.githubusercontent.com/8374843/50969931-353e0e80-14e0-11e9-8d03-353e5596e945.png)

 @mleguenD4G @martindaniel4

**Comment by martindaniel4** [comment]
@armgilles Tu as combien de patients pour lesquels tu n'as pas de `heure_declampage_cote2` ? 

@julienfessler, @mleguenD4G - y a t il une variable qu'on peut utiliser pour savoir s'il s'agit d'une opération avec un seul poumon?

**Comment by martindaniel4** [comment]
Ah ouf c'est pas énorme. Tu n'as pas d'autres heures incohérentes? 

Pour la différence entre nombre de patients static vs dynamiques, c'est attendu (cf [comment de Morgan hier](https://github.com/dataforgoodfr/batch_5_transplant/pull/58#issue-243465579))

**Comment by armgilles** [comment]
Non pour l'instant j'ai que ça. Si je vois d'autres choses, je reviens par ici ;)

**Comment by armgilles** [comment]
@Max-Pol @martindaniel4 

Est ce que ça vous va ce type de features pour savoir si on à déjà effectué un déclampage ?

+ `is_done_declampage_cote1` : 
     + 0 - pas de declampage_cote1
     + 1 - declampage éffectué pour declampage_cote1

+ `is_done_declampage_cote2` : 
     + 0 - pas de declampage_cote2
     + 1 - declampage éffectué pour declampage_cote2

Par exemple pour le patient n°1, son 1er declampage à eu lieu à 7h20

![image](https://user-images.githubusercontent.com/8374843/50972931-0a57b880-14e8-11e9-9dea-e3d0e25f6871.png)

puis le second declampage à 9h08 : 

![image](https://user-images.githubusercontent.com/8374843/50973025-3e32de00-14e8-11e9-9340-4df244d624e9.png)

Dites moi ce que vous en pensez ?

**Comment by martindaniel4** [comment]
Yes, ca me parait bien! @armgilles 

détail pour le nom, est ce que c'est pas un peu plus simple `declampage_cote2_done` vs `is_done_declampage_cote2` ?

**Comment by armgilles** [comment]
+ 1 pour le naming.

**Comment by martindaniel4** [comment]
Tu l'intégres ensuite dans `get_dynamic` de la classe `Dataset`? https://github.com/dataforgoodfr/batch_5_transplant/blob/master/transplant/data/dataset.py#L58

**Comment by armgilles** [comment]
Hum c'est une bonne question...

J'ai besoin des données statiques pour avoir les heures de declampage. Le problème c'est que ces données sont supprimé dans `get_static` à ce [niveau](https://github.com/dataforgoodfr/batch_5_transplant/blob/master/transplant/data/dataset.py#L52). Je ne peux donc pas les obtenir dans `get_dynamic`.

+ Idée 1 : revoir `get_static` & `get_dynamic` pour permettre de faire ce features engi
+ idée 2 : faire une fonction indépendante qui sera call à la fin de `get_dynamic` pour les dateframes `train`& `test` [par ici je pense](https://github.com/dataforgoodfr/batch_5_transplant/blob/master/transplant/data/dataset.py#L75) et qui chargera les données statiques pour les merge.
+ Autres idées ?

**Comment by martindaniel4** [comment]
@armgilles pourquoi tu ne récupères pas le df_static avec: 

```python
df_static = pd.read_csv(PATH_STATIC_CLEAN)
```

**Comment by armgilles** [comment]
J'ai trouvé des erreurs dans mon codes actuellement. Si la personne arrive tard dans la journée au bloc. La fonction actuelle mettra toujours 1 dans `declampage_cote1_done` & `declampage_cote2_done`

Exemple patient 245 : 

![image](https://user-images.githubusercontent.com/8374843/50985109-d12d4180-1503-11e9-9605-035b20a57eae.png)

La date du 1er déclampage est à `05h07` le 2016-02-03 (et non le 2016-02-02).

WIP

**Comment by armgilles** [comment]
Le problème lié au patient `245` est fix avec https://github.com/dataforgoodfr/batch_5_transplant/pull/60/commits/3e31a76d1f710336bdde98fdad21abdb17115282

Je recherche maintenant la date de début d'opération (données statiques) et la condition pour la création des `Heure_declampage_cote`est maintenant plus contraignante ([ici](https://github.com/dataforgoodfr/batch_5_transplant/pull/60/files#diff-cf76706c4b7ce4eedaf5f43de6ef5f3eR134)).

Par contre cela ouvre de nouveaux problèmes...

- [ ] Certain patient n'ont pas d'heure de début d'opération `heure_arrivee_bloc`
- [ ] Un patient (`227`) à une date d'opération supérieur au données dynamiques

### Absence d'heure de début d'opération : 

Dans les données statiques : 

![image](https://user-images.githubusercontent.com/8374843/51031403-c8d51500-159c-11e9-8c74-e2d737bdcaa0.png)

### Mauvaise date de début d'opération : 

le Patient `227` à un début de date d'opération le `2015-10-19 22:28:00` mais ses données dynamiques temporelle s'arrête le `2015-10-19 16:11:00` ce qui provoque une mauvaise création de données pour `declampage_cote1_done`  & `declampage_cote2_done`

On va y arriver à force ! 👍

**Comment by mleguenD4G** [comment]
du retard ce soir 
je pourrais avoir les BIS mansuant pour samedi si cela allait
pouvez vous me donner les numéros - je ne retrouve pas l'issue
morgan
Dr Morgan Le Guen
Anesthésiste-Réanimateur
Hôpital Foch, Suresnes

DECT: + 33 1 46 25 29 98
tél: + 33 1 46 25 24 33 
-----GILLES Armand <notifications@github.com> a écrit : ----- 

A : dataforgoodfr/batch_5_transplant <batch_5_transplant@noreply.github.com>De : GILLES Armand <notifications@github.com>Date : 10/01/2019 15:00Cc: mleguenD4G <m.leguen@hopital-foch.org>, Mention <mention@noreply.github.com>Objet : Re: [dataforgoodfr/batch_5_transplant] Encoding des heures evenements (clampage, declampage) (#56)
@Max-Pol @martindaniel4
Est ce que ça vous va ce type de features pour savoir si on à déjà effectué un déclampage ?


is_done_declampage_cote1 :

0 - pas de declampage_cote1
1 - declampage éffectué pour declampage_cote1

is_done_declampage_cote2 :

0 - pas de declampage_cote2
1 - declampage éffectué pour declampage_cote2
Par exemple pour le patient n°1, son 1er declampage à eu lieu à 7h20

puis le second declampage à 9h08 :

Dites moi ce que vous en pensez ?

**Comment by mleguenD4G** [comment]
pour répondre concernant les horaires déclampages
- patient 47, 154, 242, 278, 371, 381: 1 seul poumon --> la décision se prend donc de façon identique à partir du déclampage 1 
- patient 371; horaire du déclampage 02:10
- patient 358: déclampage 1: 19:30  / déclampage 2: 21:40
