### ISSUE TITLE
[Donnees Dynamiques] Mauvaise temporalité  pour des patients

### ISSUE THREAD

**Issue by armgilles** [dataforgoodfr/batch_5_transplant#62]
Les données dynamique du patient `359` sont problématiques, son opération est sur 4 jours avec énormément d'absence de données (temporelle)

![image](https://user-images.githubusercontent.com/8374843/50986478-3afb1a80-1507-11e9-8436-7ae0ef0edabf.png)

Est ce que l'on doit supprimer ce patient ou bien revoir son extraction ?

@martindaniel4 , @mleguenD4G

**Comment by martindaniel4** [comment]
@armgilles il n'y a pas un problème dans la fonction qui crée la valeur time? 

Je remarque dans le set statique que : 

```
df_static = df = pd.read_csv(PATH_STATIC_CLEAN)
df_static[df_static['id_patient'] == 359][['date_transplantation', 'date_sortie_bloc']]
```

renvoie: 

id_patient | date_transplantation | date_sortie_bloc
--- | --- | ---
359|2017-09-14 | 2017-09-15

Donc ce patient serait sortie du bloc le `2017-09-15`

**Comment by martindaniel4** [comment]
@Max-Pol je pense qu'il y a un problème au sein de la fonction `correct_date_shift` - https://github.com/dataforgoodfr/batch_5_transplant/blob/master/transplant/data/build_clean_from_raw_data.py#L103

**Comment by Max-Pol** [comment]
Attention @martindaniel4, cette fonction correct_date_shift est ma plus grande fierté :1st_place_medal: !

Elle suppose que les données dynamiques soient dans l'ordre chronologique, or pour le patient en question on voit dans Bloc2D4G.xls des "boucles" (copier ci-dessous). Les données sont corrompus, il y a superposition de timestamp... Il faudrait corriger cette erreur sur les xls.

id_patient | time
359 | 12:09
359 | 12:10
359 | 12:11
359 | 12:12
359 | 12:13
359 | 12:14
359 | 12:15
359 | 12:16
359 | 12:17
359 | 12:18
359 | 12:19
359 | 12:20
359 | 12:21
359 | 12:22
359 | 12:23
359 | 12:24
359 | 12:25
359 | 12:26
359 | 12:27
359 | 12:28
359 | 12:29
359 | 12:30
359 | 12:31
359 | 12:32
359 | 12:33
359 | 12:34
359 | 12:35
359 | 12:36
359 | 12:37
359 | 12:38
359 | 12:39
359 | 12:40
359 | 12:41
359 | 12:42
359 | 12:43
359 | 12:44
359 | 12:45
359 | 12:46
359 | 12:47
359 | 12:48
359 | 12:49
359 | 12:50
359 | 12:51
359 | 12:52
359 | 12:53
359 | 12:54
359 | 12:55
359 | 12:56
359 | 12:57
359 | 12:58
359 | 12:59
359 | 13:00
359 | 13:01
359 | 13:02
359 | 13:03
359 | 13:04
359 | 13:05
359 | 13:11
359 | 13:12
359 | 13:13
359 | 13:14
359 | 13:15
359 | 13:16
359 | 13:17
359 | 13:18
359 | 13:19
359 | 13:20
359 | 13:21
359 | 13:22
359 | 13:23
359 | 13:24
359 | 13:25
359 | 13:26
359 | 13:27
359 | 13:28
359 | 13:29
359 | 13:30
359 | 13:31
359 | 13:32
359 | 13:33
359 | 13:34
359 | 13:35
359 | 13:36
359 | 13:37
359 | 13:38
359 | 13:39
359 | 13:40
359 | 13:41
359 | 13:42
359 | 13:43
359 | 13:44
359 | 13:45
359 | 13:46
359 | 13:47
359 | 13:48
359 | 13:49
359 | 13:50
359 | 13:51
359 | 13:52
359 | 13:53
359 | 13:54
359 | 13:55
359 | 13:56
359 | 13:57
359 | 13:58
359 | 13:59
359 | 14:00
359 | 14:01
359 | 14:02
359 | 14:03
359 | 14:04
359 | 14:05
359 | 14:06
359 | 14:07
359 | 14:08
359 | 14:09
359 | 14:10
359 | 14:11
359 | 14:12
359 | 14:13
359 | 14:14
359 | 14:15
359 | 14:16
359 | 14:17
359 | 14:18
359 | 14:19
359 | 14:20
359 | 14:21
359 | 14:22
359 | 14:23
359 | 14:24
359 | 14:25
359 | 14:26
359 | 14:27
359 | 14:28
359 | 14:29
359 | 14:30
359 | 14:31
359 | 14:32
359 | 14:33
359 | 14:34
359 | 14:35
359 | 14:36
359 | 14:37
359 | 14:38
359 | 14:39
359 | 14:40
359 | 14:41
359 | 14:42
359 | 14:43
359 | 14:44
359 | 14:45
359 | 14:46
359 | 14:47
359 | 14:48
359 | 14:49
359 | 11:35
359 | 11:36
359 | 11:37
359 | 11:38
359 | 11:39
359 | 11:40
359 | 11:41
359 | 11:42
359 | 11:43
359 | 11:44
359 | 11:45
359 | 11:46
359 | 11:47
359 | 11:48
359 | 11:49
359 | 11:50
359 | 11:51
359 | 11:52
359 | 11:53
359 | 11:54
359 | 11:55
359 | 11:56
359 | 11:57
359 | 11:58
359 | 11:59
359 | 12:00
359 | 12:01
359 | 12:02
359 | 12:03
359 | 12:04
359 | 12:05
359 | 12:06
359 | 12:07
359 | 12:08
359 | 12:09
359 | 12:10
359 | 12:11
359 | 12:12
359 | 12:13
359 | 12:14
359 | 12:15
359 | 12:16
359 | 12:17
359 | 12:18
359 | 12:19
359 | 12:20
359 | 12:21
359 | 12:22
359 | 12:24
359 | 12:25
359 | 12:26
359 | 12:27
359 | 12:28
359 | 12:29
359 | 12:30
359 | 12:31
359 | 12:32
359 | 12:33
359 | 12:34
359 | 12:35
359 | 12:36
359 | 12:37
359 | 12:38
359 | 12:39
359 | 12:40
359 | 12:41
359 | 12:42
359 | 12:43
359 | 12:44
359 | 12:45
359 | 12:46
359 | 12:47
359 | 12:48
359 | 12:49
359 | 12:50
359 | 12:51
359 | 12:52
359 | 12:53
359 | 12:54
359 | 12:55
359 | 12:56
359 | 12:57
359 | 12:58
359 | 12:59
359 | 13:00
359 | 13:01
359 | 13:02
359 | 13:03
359 | 13:04
359 | 13:05
359 | 13:06
359 | 13:07
359 | 13:08
359 | 13:09
359 | 13:10
359 | 13:11
359 | 13:12
359 | 13:13
359 | 13:14
359 | 13:15
359 | 13:16
359 | 13:17
359 | 13:18
359 | 13:19
359 | 13:20
359 | 13:21
359 | 13:22
359 | 13:23
359 | 13:24
359 | 13:25
359 | 13:26
359 | 13:27
359 | 13:28
359 | 13:29
359 | 13:30
359 | 13:31
359 | 13:32
359 | 13:33
359 | 13:34
359 | 13:35
359 | 13:36
359 | 13:37
359 | 13:38
359 | 13:39
359 | 13:40
359 | 13:41
359 | 13:42
359 | 13:43
359 | 13:44
359 | 13:45
359 | 13:46
359 | 13:47
359 | 13:48
359 | 13:49
359 | 13:50
359 | 13:51
359 | 13:52
359 | 13:53
359 | 13:54
359 | 13:55
359 | 13:56
359 | 13:57
359 | 13:58
359 | 13:59
359 | 14:00
359 | 14:01
359 | 14:02
359 | 14:03
359 | 14:04
359 | 14:05
359 | 14:06
359 | 14:07
359 | 14:08
359 | 14:09
359 | 14:10
359 | 14:11
359 | 14:12
359 | 14:13
359 | 14:14
359 | 14:15
359 | 14:16
359 | 14:17
359 | 14:18
359 | 14:19
359 | 14:20
359 | 14:21
359 | 14:22
359 | 14:23
359 | 14:24
359 | 14:25
359 | 14:26
359 | 14:27
359 | 14:28
359 | 14:29
359 | 14:30
359 | 14:31
359 | 14:32
359 | 14:33
359 | 11:35
359 | 11:36
359 | 11:37
359 | 11:38
359 | 11:39
359 | 11:40
359 | 11:41
359 | 11:42
359 | 11:43
359 | 11:44
359 | 11:45
359 | 11:46
359 | 11:47
359 | 11:48
359 | 11:49
359 | 11:50
359 | 11:51
359 | 11:52
359 | 11:53
359 | 11:54
359 | 11:55
359 | 11:56
359 | 11:57
359 | 11:58
359 | 11:59
359 | 12:00
359 | 12:01
359 | 12:02
359 | 12:03
359 | 12:04
359 | 12:05
359 | 12:06
359 | 12:07
359 | 12:11
359 | 12:12
359 | 12:13
359 | 12:14
359 | 12:15
359 | 12:16
359 | 12:17
359 | 12:18
359 | 12:19
359 | 12:20
359 | 12:21
359 | 12:22
359 | 12:23
359 | 12:24
359 | 12:25
359 | 12:26
359 | 12:27
359 | 12:28
359 | 12:29
359 | 12:30
359 | 12:31
359 | 12:32
359 | 12:33
359 | 12:34
359 | 12:35
359 | 12:36
359 | 12:37
359 | 12:38
359 | 12:39
359 | 12:40
359 | 12:41
359 | 12:42
359 | 12:43
359 | 12:44
359 | 12:45
359 | 12:46
359 | 12:47
359 | 12:48
359 | 12:49
359 | 12:50
359 | 12:51
359 | 12:52
359 | 12:53
359 | 12:54
359 | 12:55
359 | 12:56
359 | 12:57
359 | 12:58
359 | 12:59
359 | 13:00
359 | 13:01
359 | 13:02
359 | 13:03
359 | 13:04
359 | 13:05
359 | 13:06
359 | 13:07
359 | 13:08
359 | 13:09
359 | 13:10
359 | 13:11
359 | 13:12
359 | 13:13
359 | 13:14
359 | 13:15
359 | 13:16
359 | 13:17
359 | 13:18
359 | 13:19
359 | 13:20
359 | 13:21
359 | 9:27
359 | 9:28
359 | 9:29
359 | 9:30
359 | 9:31
359 | 9:32
359 | 9:33
359 | 9:34
359 | 9:35
359 | 9:36
359 | 9:37
359 | 9:38
359 | 9:39
359 | 9:40
359 | 9:41
359 | 9:42
359 | 9:43
359 | 9:44
359 | 9:45
359 | 9:46
359 | 9:47
359 | 9:48
359 | 9:49
359 | 9:50
359 | 9:51
359 | 9:52
359 | 9:53
359 | 9:54
359 | 9:55
359 | 9:56
359 | 9:57
359 | 9:58
359 | 9:59
359 | 10:00
359 | 10:01
359 | 10:02
359 | 10:03
359 | 10:04
359 | 10:05
359 | 10:06
359 | 10:07
359 | 10:08
359 | 10:09
359 | 10:14
359 | 10:15
359 | 10:16
359 | 10:17
359 | 10:18
359 | 10:19
359 | 10:20
359 | 10:21
359 | 10:22
359 | 10:23
359 | 10:24
359 | 10:25
359 | 10:26
359 | 10:27
359 | 10:28
359 | 10:29
359 | 10:30
359 | 10:31
359 | 10:32
359 | 10:33
359 | 10:34
359 | 10:35
359 | 10:36
359 | 10:37
359 | 10:38
359 | 10:39
359 | 10:40
359 | 10:41
359 | 10:42
359 | 10:43
359 | 10:44
359 | 10:45
359 | 10:46
359 | 10:47
359 | 10:48
359 | 10:49
359 | 10:50
359 | 10:51
359 | 10:52
359 | 10:53
359 | 10:54
359 | 10:55
359 | 10:56
359 | 10:57
359 | 10:58
359 | 10:59

**Comment by martindaniel4** [comment]
Cette fonction est un chef d'oeuvre @Max-Pol 🎨

Cf discussion avec Morgan. On pourrait exporter `date` + `heure` pour résoudre ce problème.
