### ISSUE TITLE
[Data Quality] Erreur dans la fonction `correct_date_shift` ? 

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/batch_5_transplant#63]
En suivant https://github.com/dataforgoodfr/batch_5_transplant/issues/62 relevé par @armgilles, il me semble que des patients ont des valeurs `time` anormales par rapport à la date de sortie bloc. Je me demande s'il n'y a pas une erreur dans la fonction `correct_date_shift` qui créé la variable. 

@Max-Pol qu'en penses tu? 

Voici une liste de patient dont la difference entre la variable `time` et `date_sortie_bloc` me parait suspecte: 

id_patient | diff
-- | --
285 | -4 days +13:02:00
36 | -3 days +05:07:00
151 | -3 days +12:37:00
359 | -3 days +13:01:00
349 | -3 days +22:09:00
283 | -3 days +22:37:00
325 | -3 days +23:25:00
275 | -2 days +01:03:00
180 | -2 days +04:40:00
155 | -2 days +05:01:00
49 | -2 days +06:03:00
122 | -2 days +06:34:00
186 | -2 days +08:11:00
323 | -2 days +08:34:00
328 | -2 days +09:59:00
154 | -2 days +10:20:00
351 | -2 days +11:54:00
197 | -2 days +11:59:00
176 | -2 days +12:13:00
246 | -2 days +12:16:00
306 | -2 days +12:24:00
295 | -2 days +13:25:00
256 | -2 days +15:02:00
145 | -2 days +15:03:00
210 | -2 days +15:09:00
125 | -2 days +15:38:00
100 | -2 days +16:22:00
149 | -2 days +16:55:00
393 | -2 days +17:21:00
136 | -2 days +17:44:00

**Comment by armgilles** [comment]
J'ai regardé dans les données source (raw) pour en avoir le coeur net (`Bloc2D4G.xls` pour le patient `359`)

![image](https://user-images.githubusercontent.com/8374843/50989811-a1386b00-1510-11e9-9081-fdabdcd6fa55.png)

Apriori cela semble venir des données sources :/

**Comment by Max-Pol** [comment]
`correct_date_shift` suppose que les time soient dans l'ordre chronologique.

Manifestement, ce n'est pas toujours le cas : il y a des retours en arrière, voir des lignes avec le même timestamp, des sauts temporels... J'ai bien peur qu'il faille regarder au cas par cas.

Le plus simple et le plus sûr serait de refaire l'export de la base de l'hôpital en `.xls` pour ces patients, et même pour tous les patients. Ce fichier a l'air **bourré d'erreurs**, j'ai l'impression qu'on commence seulement à voir le bout de l'iceberg. On passerait sûrement beaucoup moins de temps en allant à l'hôpital une aprem et en refaisant l'export au propre de manière automatisé, plutôt que de traiter une à une les errreurs qui arrivent... Ça vaut le coup de voir si c'est faisable.

**Comment by martindaniel4** [comment]
F*ck c'est relou ça. On ne peut pas vraiment ordonner non plus car on n'a pas la date dans les timestamp.

Je viens d'en discuter avec Antoine, en effet on pourrait peut être refaire un export depuis la base Page maker. 

@mleguenD4G - comment as tu réalisé l'export pour les données Bloc ? Est-ce un export par patient que tu as ensuite collé dans l'Excel?

**Comment by mleguenD4G** [comment]
c'est un export en xls direct qui agrège ensemble toutes les passages dans le bloc depuis 2012.il faut ensuite extraire la transplantation pulmonaireje peux vous donner l'horodatage si cela pose problème - je m'y étais pas risqué pour des raisons d'anonymat (en craquant la programmation du bloc, vous retrouvez qui est qui...) et à l'époque c'était touchy avec l'administration....Dr Morgan Le GuenAnesthésiste-RéanimateurHôpital Foch, SuresnesDECT: + 33 1 46 25 29 98tél: + 33 1 46 25 24 33-----Martin Daniel <notifications@github.com> a écrit : -----A : dataforgoodfr/batch_5_transplant <batch_5_transplant@noreply.github.com>De : Martin Daniel <notifications@github.com>Date : 10/01/2019 23:17Cc: mleguenD4G <m.leguen@hopital-foch.org>, Mention <mention@noreply.github.com>Objet : Re: [dataforgoodfr/batch_5_transplant] [Data Quality] Erreur dans la fonction `correct_date_shift` ?  (#63)F*ck c'est relou ça. On ne peut pas vraiment ordonner non plus car on n'a pas la date dans les timestamp.

Je viens d'en discuter avec Antoine, en effet on pourrait peut être refaire un export depuis la base Page maker.

@mleguenD4G - comment as tu réalisé l'export pour les données Bloc ? Est-ce un export par patient que tu as ensuite collé dans l'Excel?

**Comment by armgilles** [comment]
@mleguenD4G 

Est ce que par hasard si on refait un export, l'on pourrait ajouter dans les données statiques des patients la date des déclampages (en plus des heure `Heure_declampage_cote1` & `Heure_declampage_cote1`) ? Je suppose que cette donnée existe mais que pour des raisons d'anonymat expliqué plus haut, elle n'a pas été prise.

Le fait de ne pas avoir le jour des évènements de déclampage provoque des complications techniques lorsque que l'opération se déroule sur plusieurs jours (cf https://github.com/dataforgoodfr/batch_5_transplant/issues/56#issuecomment-453178528)
