### ISSUE TITLE
Doc de sélection de variable non sécurisé

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch_5_transplant#97]
Hello la team Data4Good, 
dans le notebook [PCA Clustering](https://github.com/dataforgoodfr/batch_5_transplant/blob/master/notebooks/Data%20Exploration%20-%20PCA%20clustering.ipynb), un lien pointe vers un [Google Doc](https://docs.google.com/document/d/1XNNyPTxW1r_brAv4umtD2uMq_4AbhQcB619mGMQDSJQ/edit). C'est peut-être une illusion mais je crois qu'il n'est pas sécurisé.
Bonne journée,
Charles

**Comment by martindaniel4** [comment]
Merci Charles! Je ne vois pas trop en quoi c'est un problème ;)
